version: '3.5'
services:
  postgres-test:
    image: postgres:10.6-alpine
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - "POSTGRES_PASSWORD=postgres"
    ports:
      - 5432:5432
    networks:
      - rede

networks:
  rede:
    driver: overlay
